# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.0

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:
.PHONY : .NOTPARALLEL

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/Cellar/cmake/3.0.2/bin/cmake

# The command to remove a file.
RM = /usr/local/Cellar/cmake/3.0.2/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/novokrest/Github/Waterfall

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/novokrest/Github/Waterfall

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/Cellar/cmake/3.0.2/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/Cellar/cmake/3.0.2/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/novokrest/Github/Waterfall/CMakeFiles /Users/novokrest/Github/Waterfall/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/novokrest/Github/Waterfall/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named waterfall

# Build rule for target.
waterfall: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 waterfall
.PHONY : waterfall

# fast build rule for target.
waterfall/fast:
	$(MAKE) -f CMakeFiles/waterfall.dir/build.make CMakeFiles/waterfall.dir/build
.PHONY : waterfall/fast

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) -f CMakeFiles/waterfall.dir/build.make CMakeFiles/waterfall.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) -f CMakeFiles/waterfall.dir/build.make CMakeFiles/waterfall.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) -f CMakeFiles/waterfall.dir/build.make CMakeFiles/waterfall.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/model.o: src/model.cpp.o
.PHONY : src/model.o

# target to build an object file
src/model.cpp.o:
	$(MAKE) -f CMakeFiles/waterfall.dir/build.make CMakeFiles/waterfall.dir/src/model.cpp.o
.PHONY : src/model.cpp.o

src/model.i: src/model.cpp.i
.PHONY : src/model.i

# target to preprocess a source file
src/model.cpp.i:
	$(MAKE) -f CMakeFiles/waterfall.dir/build.make CMakeFiles/waterfall.dir/src/model.cpp.i
.PHONY : src/model.cpp.i

src/model.s: src/model.cpp.s
.PHONY : src/model.s

# target to generate assembly for a file
src/model.cpp.s:
	$(MAKE) -f CMakeFiles/waterfall.dir/build.make CMakeFiles/waterfall.dir/src/model.cpp.s
.PHONY : src/model.cpp.s

src/particlesystem.o: src/particlesystem.cpp.o
.PHONY : src/particlesystem.o

# target to build an object file
src/particlesystem.cpp.o:
	$(MAKE) -f CMakeFiles/waterfall.dir/build.make CMakeFiles/waterfall.dir/src/particlesystem.cpp.o
.PHONY : src/particlesystem.cpp.o

src/particlesystem.i: src/particlesystem.cpp.i
.PHONY : src/particlesystem.i

# target to preprocess a source file
src/particlesystem.cpp.i:
	$(MAKE) -f CMakeFiles/waterfall.dir/build.make CMakeFiles/waterfall.dir/src/particlesystem.cpp.i
.PHONY : src/particlesystem.cpp.i

src/particlesystem.s: src/particlesystem.cpp.s
.PHONY : src/particlesystem.s

# target to generate assembly for a file
src/particlesystem.cpp.s:
	$(MAKE) -f CMakeFiles/waterfall.dir/build.make CMakeFiles/waterfall.dir/src/particlesystem.cpp.s
.PHONY : src/particlesystem.cpp.s

src/shaders.o: src/shaders.cpp.o
.PHONY : src/shaders.o

# target to build an object file
src/shaders.cpp.o:
	$(MAKE) -f CMakeFiles/waterfall.dir/build.make CMakeFiles/waterfall.dir/src/shaders.cpp.o
.PHONY : src/shaders.cpp.o

src/shaders.i: src/shaders.cpp.i
.PHONY : src/shaders.i

# target to preprocess a source file
src/shaders.cpp.i:
	$(MAKE) -f CMakeFiles/waterfall.dir/build.make CMakeFiles/waterfall.dir/src/shaders.cpp.i
.PHONY : src/shaders.cpp.i

src/shaders.s: src/shaders.cpp.s
.PHONY : src/shaders.s

# target to generate assembly for a file
src/shaders.cpp.s:
	$(MAKE) -f CMakeFiles/waterfall.dir/build.make CMakeFiles/waterfall.dir/src/shaders.cpp.s
.PHONY : src/shaders.cpp.s

src/texture.o: src/texture.cpp.o
.PHONY : src/texture.o

# target to build an object file
src/texture.cpp.o:
	$(MAKE) -f CMakeFiles/waterfall.dir/build.make CMakeFiles/waterfall.dir/src/texture.cpp.o
.PHONY : src/texture.cpp.o

src/texture.i: src/texture.cpp.i
.PHONY : src/texture.i

# target to preprocess a source file
src/texture.cpp.i:
	$(MAKE) -f CMakeFiles/waterfall.dir/build.make CMakeFiles/waterfall.dir/src/texture.cpp.i
.PHONY : src/texture.cpp.i

src/texture.s: src/texture.cpp.s
.PHONY : src/texture.s

# target to generate assembly for a file
src/texture.cpp.s:
	$(MAKE) -f CMakeFiles/waterfall.dir/build.make CMakeFiles/waterfall.dir/src/texture.cpp.s
.PHONY : src/texture.cpp.s

src/utils.o: src/utils.cpp.o
.PHONY : src/utils.o

# target to build an object file
src/utils.cpp.o:
	$(MAKE) -f CMakeFiles/waterfall.dir/build.make CMakeFiles/waterfall.dir/src/utils.cpp.o
.PHONY : src/utils.cpp.o

src/utils.i: src/utils.cpp.i
.PHONY : src/utils.i

# target to preprocess a source file
src/utils.cpp.i:
	$(MAKE) -f CMakeFiles/waterfall.dir/build.make CMakeFiles/waterfall.dir/src/utils.cpp.i
.PHONY : src/utils.cpp.i

src/utils.s: src/utils.cpp.s
.PHONY : src/utils.s

# target to generate assembly for a file
src/utils.cpp.s:
	$(MAKE) -f CMakeFiles/waterfall.dir/build.make CMakeFiles/waterfall.dir/src/utils.cpp.s
.PHONY : src/utils.cpp.s

src/waterfallprogram.o: src/waterfallprogram.cpp.o
.PHONY : src/waterfallprogram.o

# target to build an object file
src/waterfallprogram.cpp.o:
	$(MAKE) -f CMakeFiles/waterfall.dir/build.make CMakeFiles/waterfall.dir/src/waterfallprogram.cpp.o
.PHONY : src/waterfallprogram.cpp.o

src/waterfallprogram.i: src/waterfallprogram.cpp.i
.PHONY : src/waterfallprogram.i

# target to preprocess a source file
src/waterfallprogram.cpp.i:
	$(MAKE) -f CMakeFiles/waterfall.dir/build.make CMakeFiles/waterfall.dir/src/waterfallprogram.cpp.i
.PHONY : src/waterfallprogram.cpp.i

src/waterfallprogram.s: src/waterfallprogram.cpp.s
.PHONY : src/waterfallprogram.s

# target to generate assembly for a file
src/waterfallprogram.cpp.s:
	$(MAKE) -f CMakeFiles/waterfall.dir/build.make CMakeFiles/waterfall.dir/src/waterfallprogram.cpp.s
.PHONY : src/waterfallprogram.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... waterfall"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/model.o"
	@echo "... src/model.i"
	@echo "... src/model.s"
	@echo "... src/particlesystem.o"
	@echo "... src/particlesystem.i"
	@echo "... src/particlesystem.s"
	@echo "... src/shaders.o"
	@echo "... src/shaders.i"
	@echo "... src/shaders.s"
	@echo "... src/texture.o"
	@echo "... src/texture.i"
	@echo "... src/texture.s"
	@echo "... src/utils.o"
	@echo "... src/utils.i"
	@echo "... src/utils.s"
	@echo "... src/waterfallprogram.o"
	@echo "... src/waterfallprogram.i"
	@echo "... src/waterfallprogram.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

